# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: parse_resource 1.9.0 ruby lib
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

Gem::Specification.new do |s|
  s.name = "parse_resource"
  s.version = "1.9.0"

  s.require_paths = ["lib"]
  s.authors = ["Alan deLevie"]
  s.date = "2015-11-10"
  s.description = ""
  s.email = "adelevie@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]

  s.files         = `git ls-files -z`.split("\x0")
  s.homepage = "http://github.com/adelevie/parse_resource"
  s.licenses = ["MIT"]
  s.summary = "An ActiveResource-like wrapper for the Parse REST api."

  s.add_runtime_dependency 'rest-client'
  s.add_runtime_dependency 'activesupport'
  s.add_runtime_dependency 'activemodel'
  s.add_runtime_dependency 'json'
  s.add_development_dependency 'bundler', "~> 1.7"
  s.add_development_dependency "rake", "~> 10.0"
  s.add_development_dependency 'reek', "~> 1.2.8"
  s.add_development_dependency 'vcr'
  s.add_development_dependency 'webmock'
  s.add_development_dependency 'turn'
end
